development:
  adapter: postgresql
  encoding: unicode
  database: locator_development
  pool: 5
  username: tomohung
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: locator_test
  pool: 5
  username: tomohung
  password: 